### ISSUE TITLE
Question about accuracy of Figure 2

### ISSUE THREAD

**Issue by LaraVolski** [LaraVolski/Foxlights#12]
https://github.com/LaraVolski/Foxlights/blob/035a2e44cbbce435858ad2b93bd855647dfe5775/foxlights_data_analysis.Rmd#L150

Hi Kaitlyn,

I'm probably overthinking this but thought I'd ask anyway. Want to make sure this graph is correct.

In the paper we write "the mean number of coyote detections per active Foxlight period (5 weeks) was 2.1 (SD +/- 3.15, Figure 2). For inactive Foxlight periods, it was 2.45 (SD +/- 3.1, Figure 2)." We got this number because we multiplied the original RAI (0.06 and 0.07) by 35 (because 5 weeks * 7 days). I just want to make sure the graph accurately conveys this info... I think I’m getting confused because the little black line in the figure doesn’t look like it matches up with what 2.1 and 2.45 would be on the Y-axis…

Thank you!
Lara

**Comment by kaitlyngaynor** [comment]
The black line is the median, not mean, which explains the discrepancy.

I would also recommend just multiplying RAI itself by 5 in aes(), rather than changing the axis scale, since it results in a more regular interval (0, 5, 10, 15; instead of 3.5, 7, 10.5, 14). I've already made the change in the script, so just pull it and you should be set!

**Comment by LaraVolski** [comment]
Thank you!
